In [ ]:
# if use university account:
# from google.colab import drive
# drive.mount('/content/drive')
# import os
# GOOGLE_DRIVE_PATH = 'Colab/ai_scholar/'
# PATH = os.path.join('drive', 'My Drive', GOOGLE_DRIVE_PATH)
# import sys
# sys.path.append(PATH)
# print(os.listdir(PATH)) 

# if use local machine or server:
# PATH = ''
# PATH_DATA = ''

In [ ]:
import csv
import numpy as np
import sys
from pathlib import Path
import pickle
import pandas as pd
import json

In [ ]:
scholar_all = np.load(PATH+'78k_scholar_new.npy', allow_pickle=True)

In [ ]:
for scholar in scholar_all:
  if int(scholar['cites']['years'][-1]) > 2022:
    print(scholar)
    

In [ ]:
scholar_all[0]

{'citations_table': ['3563', '500', '27', '12', '55', '14'],
 'cites': {'cites': ['39',
   '47',
   '101',
   '100',
   '96',
   '117',
   '115',
   '112',
   '106',
   '118',
   '119',
   '133',
   '154',
   '186',
   '176',
   '147',
   '139',
   '124',
   '194',
   '164',
   '128',
   '143',
   '177',
   '116',
   '116',
   '94',
   '74',
   '76',
   '24'],
  'years': ['1994',
   '1995',
   '1996',
   '1997',
   '1998',
   '1999',
   '2000',
   '2001',
   '2002',
   '2003',
   '2004',
   '2005',
   '2006',
   '2007',
   '2008',
   '2009',
   '2010',
   '2011',
   '2012',
   '2013',
   '2014',
   '2015',
   '2016',
   '2017',
   '2018',
   '2019',
   '2020',
   '2021',
   '2022']},
 'co_authors': None,
 'extra_info': ['N/A',
  'No verified email',
  '<a href="/citations?view_op=search_authors&amp;hl=en&amp;mauthors=label:logic_programming" class="gsc_prf_inta gs_ibl">Logic programming</a><a href="/citations?view_op=search_authors&amp;hl=en&amp;mauthors=label:machine_learning" class="

In [ ]:
with open(PATH+"gs_scholar_new_features.jsonl") as f:
  scholars = [json.loads(line) for line in f if line.strip()]

In [ ]:
scholars[0]

{'academic': False,
 'academic_age': 31,
 'academic_lifespan': 28,
 'cit_sum_before_year': {'1994': 39,
  '1995': 86,
  '1996': 187,
  '1997': 287,
  '1998': 383,
  '1999': 500,
  '2000': 615,
  '2001': 727,
  '2002': 833,
  '2003': 951,
  '2004': 1070,
  '2005': 1203,
  '2006': 1357,
  '2007': 1543,
  '2008': 1719,
  '2009': 1866,
  '2010': 2005,
  '2011': 2129,
  '2012': 2323,
  '2013': 2487,
  '2014': 2615,
  '2015': 2758,
  '2016': 2935,
  '2017': 3051,
  '2018': 3167,
  '2019': 3261,
  '2020': 3335,
  '2021': 3411,
  '2022': 3435},
 'citation_table': ['3539', '27'],
 'domain_labels': ['logic_programming',
  'machine_learning',
  'natural_language_processing'],
 'gender': 'F',
 'gs_sid': 'IIrX5SMAAAAJ',
 'organization': 'N/A',
 'organization_code': None,
 'paper_num': 151}

In [ ]:
with open(PATH+"gs_scholars.jsonl") as f:
  scholars_jsonl = [json.loads(line) for line in f if line.strip()]

In [ ]:
scholars_jsonl[0]

{'citations_table': ['293', '122', '9', '6', '8', '5'],
 'cites': {'cites': ['1',
   '1',
   '15',
   '16',
   '13',
   '17',
   '19',
   '29',
   '19',
   '27',
   '11',
   '18',
   '24',
   '23',
   '18',
   '16',
   '23'],
  'years': ['2005',
   '2006',
   '2007',
   '2008',
   '2009',
   '2010',
   '2011',
   '2012',
   '2013',
   '2014',
   '2015',
   '2016',
   '2017',
   '2018',
   '2019',
   '2020',
   '2021']},
 'co_authors': None,
 'extra_info': ['Ree Technology',
  'No verified email',
  'computer visionmachine learningcontent based multimedia retrieval'],
 'name': 'Sebastian Gerke',
 'papers': [['https://scholar.google.com/citations?view_op=view_citation&hl=en&user=DeP0anAAAAAJ&alert_preview_top_rm=2&citation_for_view=DeP0anAAAAAJ:2osOgNQ5qMEC',
   'ActiveRDF: Object-oriented semantic web programming',
   ['E Oren, R Delbru, S Gerke, A Haller, S Decker',
    'Proceedings of the 16th international conference on World Wide Web, 817-824'],
   '121',
   'https://scholar.google.

In [ ]:
scholars_old = np.load(PATH+"73k_scholar_21042022.npy", allow_pickle=True)

In [ ]:
cnt = 0
for scholar in scholars_old:
  if scholar not in scholar_all:
    print(cnt)
    break
  cnt += 1

In [ ]:
tmp_dict = {1:1, 2:2, 3:3}
tmp_dict.pop(3, None)
tmp_dict

{1: 1, 2: 2}

In [ ]:
citations = np.array([3,2,5,63,78,40])
n=6
array = np.arange(1, n+1)
result = citations >= array.reshape((-1,1))
# result = result.sum(axis=1) 

In [ ]:
result

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True]])

In [ ]:
result = result.sum(axis=1)
result

array([6, 6, 5, 4, 4, 3])

In [ ]:
result = result >= array
result

array([ True,  True,  True,  True, False, False])

In [ ]:
array[result]

array([1, 2, 3, 4])